version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: oauth-test-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: oauth-test
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    container_name: oauth-test-redis
    ports:
      - "6379:6379"

# docker-compose up -d