# Spring Security OAuth2 클라이언트 설정
spring:
  security:
    oauth2:
      client:
        registration:
          github: # 우리가 사용할 OAuth 제공자 ID (callback URL의 마지막 부분과 일치)
            client-id: [ client-id ] # GitHub에서 복사한 Client ID
            client-secret: [ client-secret ] # GitHub에서 복사한 Client Secret
            scope: # GitHub에 요청할 사용자 정보의 범위
              - read:user
              - user:email

  # 데이터베이스(MySQL) 연동 설정
  datasource:
    url: jdbc:mysql://localhost:3306/oauth-test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # 사용할 데이터베이스 주소 및 이름
    username: root # MySQL 사용자 이름
    password: 1234 # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379

# JWT 설정
jwt:
  secret: [ jwt-secret ] #  512비트(64바이트) 이상의 길이 필수
  access-token-expiry: 3600000 # 1시간 (ms)
  refresh-token-expiry: 604800000 # 7일 (ms)
  auth-code-expiry: 60000 # 5분 (ms)