spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: [YOUR_GITHUB_CLIENT_ID]
            client-secret: [YOUR_GITHUB_CLIENT_SECRET]
            scope:
              - read:user
              - user:email
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_db?serverTimezone=Asia/Seoul&characterEncoding=UTF--8
    username: [YOUR_MYSQL_USERNAME]
    password: [YOUR_MYSQL_PASSWORD]
    driver-class-name: com.mysql.cj.jdbc.Driver